#!/bin/bash

ENV_FILE="./.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env file..."

    POSTGRES_USER=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
    POSTGRES_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12)
    POSTGRES_DB="cavedb"
    REDIS_URL="redis://redis"
    SECRET_KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64)
    ALGORITHM="HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES="60"
    REFRESH_TOKEN_EXPIRE_HOURS="72"
    PORT="8080"
    MODE="single"
    CORE_LIMIT=True

    cat <<EOF > "$ENV_FILE"
### Database Config ###
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SQLALCHEMY_DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@postgres/\${POSTGRES_DB}
REDIS_URL=$REDIS_URL
### Keys and Authentication ###
SECRET_KEY=$SECRET_KEY
ALGORITHM=$ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
REFRESH_TOKEN_EXPIRE_HOURS=$REFRESH_TOKEN_EXPIRE_HOURS
### Server Config (See README.md) ###
PORT=$PORT
MODE=$MODE
CORE_LIMIT=$CORE_LIMIT
EOF

    echo "########## .env file created successfully. ##########"
    sleep 2 # just giving a little space to docker to read the file
else
    echo "########## .env file already exists. Skipping creation. ##########"
fi
