#!/bin/bash

ENV_FILE="./.env"

print_color() {
    COLOR="$1"
    TEXT="$2"
    echo -e "${COLOR}${TEXT}${NC}"
}

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

print_separator() {
    print_color "$BLUE" "===================================================="
}

# Call create_env script
./create_env

print_separator

print_color "$BLUE" "########## Pulling Docker Images ##########"
docker compose pull || print_color "$RED" "Failed to pull Docker images!"

print_separator

print_color "$BLUE" "########## Starting the Application in 3 Seconds... ##########"
print_color "$YELLOW" "########## CTRL-C To Interrupt ##########"
sleep 3
docker compose up -d || print_color "$RED" "Failed to start the application!"

print_separator
print_color "$GREEN" "########## Application Started Successfully ##########"
