-- Arcade Machines and Accessories
INSERT INTO component_type (name, hardware_category_id)
VALUES ('Arcade Control Panel', 1),
       ('Arcade Light Gun', 1),
       ('Arcade Marquee', 1),
       ('Arcade Monitor', 1),
       ('Arcade Pedestal Stand', 1),
       ('Arcade Power Cord', 1),
       ('Arcade Speaker Grill', 1),
       ('Arcade T-Molding', 1),
       ('Arcade Ticket Dispenser', 1),
       ('Arcade Token Slot', 1),
       ('Arcade Trackball', 1),
       ('Arcade Transformer', 1),
       ('Arcade Wiring Kit', 1),
       ('Cabinet Coin Box', 1),
       ('Cabinet Coin Door', 1),
       ('Cabinet Coin Mechanism', 1),
       ('Cabinet Coin Slot', 1),
       ('Cabinet Control Panel Overlay', 1),
       ('Cabinet Control Panel Sticker', 1),
       ('Cabinet Display Board', 1),
       ('Cabinet Display Monitor', 1),
       ('Cabinet Display Stand', 1),
       ('Cabinet Lock Kit', 1),
       ('Cabinet Marquee Light', 1),
       ('Cabinet Power Switch', 1),
       ('Cabinet Replacement Joystick', 1),
       ('Cabinet Replacement Buttons', 1),
       ('Cabinet Side Panel', 1),
       ('Cabinet Side Trim', 1),
       ('Cabinet Stool', 1),
       ('Cabinet Transformer', 1),
       ('Coin Acceptor Bezel', 1),
       ('Coin Acceptor Mount', 1),
       ('Coin Acceptor Plate', 1),
       ('Coin Acceptor Wiring Harness', 1),
       ('Coin Box Lock', 1),
       ('Coin Counter Display', 1),
       ('Coin Door Bezel', 1),
       ('Coin Door Lock Kit', 1),
       ('Coin Door Mounting Plate', 1),
       ('Coin Entry Plate', 1),
       ('Coin Token Holder', 1),
       ('Coin Token Slot Cover', 1),
       ('Coin Token Tray', 1),
       ('Coin Token Vault', 1),
       ('Game Conversion Kit Cabinet', 1),
       ('Game Conversion Kit PCB', 1),
       ('Game Conversion Kit Wiring Harness', 1),
       ('Joystick Ball Top', 1),
       ('Joystick Cable', 1),
       ('Joystick Dust Cover', 1),
       ('Joystick Handle Grip', 1),
       ('Joystick Restrictor Gate', 1),
       ('Joystick Shaft Cover', 1),
       ('Joystick Wiring Harness', 1),
       ('Light Gun Holster', 1),
       ('Light Gun Sensor Bar', 1),
       ('Light Gun Stand', 1),
       ('Marquee Bracket', 1),
       ('Marquee Plexiglass', 1),
       ('Marquee Retainer', 1),
       ('Marquee Trim', 1),
       ('Monitor Bezel', 1),
       ('Monitor Control Board', 1),
       ('Monitor Frame', 1),
       ('Monitor Mounting Bracket', 1),
       ('Monitor Neck Board', 1),
       ('Monitor Power Cord', 1),
       ('Monitor Power Supply', 1),
       ('Monitor Stand', 1),
       ('Monitor Wiring Harness', 1),
       ('Pedestal Cabinet Base', 1),
       ('Pedestal Cabinet Shelf', 1),
       ('Pedestal Cabinet Top', 1),
       ('Pedestal Cabinet Trim', 1),
       ('Power Supply Cord', 1),
       ('Power Supply Mounting Bracket', 1),
       ('Power Supply Wiring Harness', 1),
       ('Speaker Amplifier', 1),
       ('Speaker Mounting Bracket', 1),
       ('Speaker Wiring Harness', 1),
       ('T-Molding Cutter', 1),
       ('T-Molding Trim', 1),
       ('Token Dispenser Bezel', 1),
       ('Token Dispenser Mount', 1),
       ('Token Dispenser Plate', 1),
       ('Token Dispenser Wiring Harness', 1),
       ('Token Slot Bezel', 1),
       ('Token Slot Cover', 1),
       ('Token Slot Mounting Plate', 1),
       ('Token Slot Wiring Harness', 1),
       ('Trackball Bezel', 1),
       ('Trackball Mounting Plate', 1),
       ('Trackball Roller', 1),
       ('Trackball Sensor Board', 1),
       ('Trackball Stand', 1),
       ('Trackball Wiring Harness', 1),
       ('Transformer Mounting Bracket', 1),
       ('Transformer Wiring Harness', 1),
       ('Wiring Harness Clamp', 1),
       ('Wiring Harness Splitter', 1),
       ('Wiring Harness Tester', 1),
       ('Wiring Harness Wrap', 1) ON CONFLICT
    DO NOTHING;