INSERT INTO hardware_category (name)
VALUES ('Audio and Video Equipment')
ON CONFLICT
    DO NOTHING;
-- Audio and Video Equipment
INSERT INTO component_type (name, hardware_category_id)
VALUES ('3.5mm Audio Cable', 2),
       ('4K HDMI Cable', 2),
       ('4K Ultra HD Blu-ray Player', 2),
       ('5.1 Surround Sound System', 2),
       ('7.1 Surround Sound System', 2),
       ('7.2 Surround Sound Receiver', 2),
       ('8K HDMI Cable', 2),
       ('A/V Receiver Amplifier', 2),
       ('Adjustable Projector Mount', 2),
       ('Adjustable Speaker Stands', 2),
       ('Amplifier Stand', 2),
       ('Audiophile Headphones', 2),
       ('Audiophile Stereo Amplifier', 2),
       ('Blu-ray Disc Changer', 2),
       ('Bluetooth Audio Adapter', 2),
       ('Bluetooth Audio Receiver', 2),
       ('Bluetooth Ceiling Speakers', 2),
       ('Bluetooth Home Theater System', 2),
       ('Bluetooth Soundbar', 2),
       ('Bluetooth Soundbar with Subwoofer', 2),
       ('Cable Clips', 2),
       ('Cable Concealer Kit', 2),
       ('Cable Cover Raceway Kit', 2),
       ('Cable Management Sleeve', 2),
       ('Ceiling Speaker Mount', 2),
       ('Center Channel Speaker', 2),
       ('Component Video Switch', 2),
       ('Digital Audio Interface', 2),
       ('Digital Audio Recorder', 2),
       ('Digital Audio Workstation', 2),
       ('Digital Coaxial Cable', 2),
       ('Digital-to-Analog Converter', 2),
       ('DJ Headphones', 2),
       ('DJ Mixer', 2),
       ('Dolby Atmos Ceiling Speakers', 2),
       ('Dolby Atmos Receiver', 2),
       ('Dolby Atmos Sound System', 2),
       ('Dual HDMI Adapter', 2),
       ('Dual HDMI Splitter', 2),
       ('Dynamic Microphone', 2),
       ('External Blu-ray Drive', 2),
       ('External Sound Card', 2),
       ('Floor Standing Speakers', 2),
       ('Gaming Projector Screen', 2),
       ('Gaming Soundbar', 2),
       ('HDMI Audio Extractor', 2),
       ('HDMI to DisplayPort Adapter', 2),
       ('HDMI to VGA Converter', 2),
       ('Home Cinema Projector', 2),
       ('Home Theater Decor', 2),
       ('Home Theater Seating', 2),
       ('Home Theater Sign', 2),
       ('In-Wall Speaker Amplifier', 2),
       ('In-Wall Speaker Bracket', 2),
       ('In-Wall Speaker Mount', 2),
       ('In-Wall Speaker Wire', 2),
       ('In-Wall Subwoofer', 2),
       ('Karaoke Microphone System', 2),
       ('Karaoke Mixer Amplifier', 2),
       ('Karaoke Mixer', 2),
       ('Karaoke System', 2),
       ('Microphone Cable', 2),
       ('Microphone Pop Filter', 2),
       ('Microphone Shock Mount', 2),
       ('Mini DisplayPort Adapter', 2),
       ('Mini Projector Screen', 2),
       ('Mini Stereo System', 2),
       ('Miniature Microphone', 2),
       ('Multi-Channel Receiver', 2),
       ('Outdoor Movie Screen', 2),
       ('Outdoor Speaker Wire', 2),
       ('Over-Ear Gaming Headphones', 2),
       ('Overhead Projector', 2),
       ('Powered Bookshelf Speakers', 2),
       ('Powered Subwoofer', 2),
       ('Projector Ceiling Bracket Kit', 2),
       ('Projector Ceiling Mount Kit', 2),
       ('Projector Hush Box', 2),
       ('Projector Lens', 2),
       ('Projector Mounting Plate', 2),
       ('Projector Screen Cleaner', 2),
       ('Projector Screen Pull Down', 2),
       ('Projector Screen Wall Mount', 2),
       ('RCA Audio Cable', 2),
       ('Remote Control Extender', 2),
       ('Smart Projector', 2),
       ('Soundbar Bracket Kit', 2),
       ('Soundbar Wall Mount Bracket', 2),
       ('Speaker Binding Post', 2),
       ('Speaker Cable Connector', 2),
       ('Speaker Stand Cover', 2),
       ('Speaker Wall Plate', 2),
       ('Stereo Headphone Adapter', 2),
       ('Surround Sound System Stand', 2),
       ('TV Antenna Amplifier', 2),
       ('TV Antenna Mast', 2),
       ('USB Sound Card', 2),
       ('Wireless Headphone Transmitter', 2),
       ('Wireless Surround Sound System', 2),
       ('XLR Cable', 2)
ON CONFLICT
    DO NOTHING;