-- Automotive Accessories
INSERT INTO component_type (name, hardware_category_id)
VALUES ('Air Filter', 3),
       ('Bike Rack', 3),
       ('Brake Pads', 3),
       ('Car Air Freshener', 3),
       ('Car Alarm System', 3),
       ('Car Audio System', 3),
       ('Car Battery', 3),
       ('Car Battery Charger', 3),
       ('Car Bike Rack', 3),
       ('Car Body Kits', 3),
       ('Car Charger', 3),
       ('Car Cleaning Kit', 3),
       ('Car Covers', 3),
       ('Car Dash Cover', 3),
       ('Car Diagnostic Scanner', 3),
       ('Car Emergency Kit', 3),
       ('Car Exhaust System', 3),
       ('Car Graphics and Decals', 3),
       ('Car Headlight Bulbs', 3),
       ('Car Horn', 3),
       ('Car Interior Lights', 3),
       ('Car Jack', 3),
       ('Car Jump Starter', 3),
       ('Car Key Finder', 3),
       ('Car LED Lighting', 3),
       ('Car Performance Chips', 3),
       ('Car Phone Mount', 3),
       ('Car Repair Tools', 3),
       ('Car Roof Basket', 3),
       ('Car Roof Box', 3),
       ('Car Seat Covers', 3),
       ('Car Seat Cushion', 3),
       ('Car Spoilers', 3),
       ('Car Sunshade', 3),
       ('Car Suspension Kit', 3),
       ('Car Tint Film', 3),
       ('Car Tire Pressure Gauge', 3),
       ('Car Trash Can', 3),
       ('Car Wash Kit', 3),
       ('Car Wax', 3),
       ('Dash Cam', 3),
       ('Engine Oil', 3),
       ('GPS Navigation System', 3),
       ('Roof Rack', 3),
       ('Spark Plugs', 3),
       ('Steering Wheel Cover', 3),
       ('Tire Chains', 3),
       ('Trailer Hitch', 3),
       ('Windshield Wipers', 3) ON CONFLICT
    DO NOTHING;
