-- Board Games and Puzzles
INSERT INTO component_type (name, hardware_category_id)
VALUES ('7 Wonders', 4),
       ('Apples to Apples', 4),
       ('Azul', 4),
       ('Azul: Stained Glass of Sintra', 4),
       ('Bananagrams', 4),
       ('Betrayal at Baldur''s Gate', 4),
       ('Betrayal at Baldur''s Gate: Haunt 61 Expansion', 4),
       ('Betrayal at Baldur''s Gate: Widow''s Walk Expansion', 4),
       ('Betrayal at House on the Hill', 4),
       ('Betrayal at House on the Hill: Widow''s Walk Expansion', 4),
       ('Battleship', 4),
       ('Carcassonne', 4),
       ('Carcassonne Expansion', 4),
       ('Carcassonne: Princess & Dragon Expansion', 4),
       ('Carcassonne: Traders & Builders Expansion', 4),
       ('Carcassonne: Traders & Barbarians Expansion', 4),
       ('Catan Board Game', 4),
       ('Catan: Cities & Knights Expansion', 4),
       ('Catan: Explorers & Pirates Expansion', 4),
       ('Catan: Seafarers Expansion', 4),
       ('Chess Set', 4),
       ('Clue', 4),
       ('Clue: Game of Thrones Edition', 4),
       ('Codenames', 4),
       ('Codenames: Duet', 4),
       ('Codenames: Pictures', 4),
       ('Connect 4', 4),
       ('Dixit', 4),
       ('Dixit Expansion', 4),
       ('Dominion', 4),
       ('Dominion Expansion', 4),
       ('Dominion: Adventures Expansion', 4),
       ('Dominion: Prosperity Expansion', 4),
       ('Exploding Kittens', 4),
       ('Exploding Kittens: Barking Kittens Expansion', 4),
       ('Exploding Kittens: Imploding Kittens Expansion', 4),
       ('Forbidden Desert', 4),
       ('Forbidden Island', 4),
       ('Hedbanz', 4),
       ('Jenga', 4),
       ('Jenga: Donkey Kong Edition', 4),
       ('King of Tokyo', 4),
       ('Kingdomino', 4),
       ('Lords of Waterdeep', 4),
       ('Love Letter', 4),
       ('Love Letter: Batman Edition', 4),
       ('Monopoly', 4),
       ('Monopoly: Fortnite Edition', 4),
       ('Munchkin', 4),
       ('Pandemic', 4),
       ('Pandemic Legacy', 4),
       ('Pandemic: In the Lab Expansion', 4),
       ('Pandemic: On the Brink Expansion', 4),
       ('Pandemic: The Fall of Rome', 4),
       ('Phase 10', 4),
       ('Pictionary', 4),
       ('Qwirkle', 4),
       ('Qwirkle: Travel Size', 4),
       ('Risk', 4),
       ('Risk: Game of Thrones Edition', 4),
       ('Risk: Lord of the Rings Edition', 4),
       ('Rummikub', 4),
       ('Rummikub: Deluxe Edition', 4),
       ('Santorini', 4),
       ('Scrabble', 4),
       ('Sequence', 4),
       ('Sequence: Deluxe Edition', 4),
       ('Set', 4),
       ('Settlers of Catan Expansion', 4),
       ('Sheriff of Nottingham', 4),
       ('Sheriff of Nottingham: Merry Men Expansion', 4),
       ('Splendor', 4),
       ('Splendor Expansion', 4),
       ('Sushi Go!', 4),
       ('Sushi Go Party!', 4),
       ('Sushi Go Party!: Soy Sauce Promo', 4),
       ('Taboo', 4),
       ('Taboo: Midnight', 4),
       ('The Game of Life', 4),
       ('The Game of Life: Empire', 4),
       ('The Resistance', 4),
       ('The Resistance: Avalon', 4),
       ('Ticket to Ride', 4),
       ('Ticket to Ride Europe', 4),
       ('Trailer Hitch', 4),
       ('Twister', 4),
       ('Uno', 4),
       ('Uno Attack', 4),
       ('Uno: Flip', 4),
       ('Uno: Giant', 4),
       ('Uno: Super Mario Edition', 4),
       ('Uno: The Legend of Zelda Edition', 4),
       ('Uno: Toy Story Edition', 4),
       ('Uno: Uno Dare', 4),
       ('Uno: Uno Emoji', 4),
       ('Uno: Uno Flip', 4),
       ('Uno: Uno Stacko', 4),
       ('Uno: Uno Showdown', 4),
       ('Uno: Uno Spin', 4),
       ('Uno: Uno Splash', 4),
       ('Uno: Uno Wild Jackpot', 4),
       ('Uno: Uno Wild Tiles', 4),
       ('Uno: Uno World''s Smallest Edition', 4),
       ('Uno: Uno Wilderness', 4),
       ('Uno: Uno: 50th Anniversary Edition', 4),
       ('Uno: Uno: Harry Potter Edition', 4),
       ('Uno: Uno: Marvel Edition', 4),
       ('Uno: Uno: The Mandalorian Edition', 4),
       ('Uno: Uno: WWE Edition', 4) ON CONFLICT
    DO NOTHING;