-- Electronic Components
INSERT INTO component_type (name, hardware_category_id)
VALUES ('Accelerometers', 7),
       ('Amplifier ICs', 7),
       ('Analog Front-End (AFE) ICs', 7),
       ('Analog-to-Digital Converters (ADCs)', 7),
       ('Anti-Static Bags', 7),
       ('Audio Interface Transceivers', 7),
       ('Bluetooth Controllers', 7),
       ('Bluetooth Modules', 7),
       ('Bluetooth Transceivers', 7),
       ('Brushless DC Motors', 7),
       ('CAN Bus Controllers', 7),
       ('CAN Bus Modules', 7),
       ('CAN Bus Transceivers', 7),
       ('Capacitance Meters', 7),
       ('Capacitors', 7),
       ('Cellular Modules', 7),
       ('Cellular Transceivers', 7),
       ('Ceramic Capacitors', 7),
       ('Character LCD Modules', 7),
       ('Chokes', 7),
       ('Circuit Breakers', 7),
       ('Clock Generator ICs', 7),
       ('Clock Generators', 7),
       ('Color Sensors', 7),
       ('Comparator ICs', 7),
       ('Connectors', 7),
       ('Crystal Oscillator Modules', 7),
       ('Crystals and Oscillators', 7),
       ('Current Sensors', 7),
       ('Current Shunt Monitors', 7),
       ('Current Transducers', 7),
       ('Digital-to-Analog Converters (DACs)', 7),
       ('Diodes', 7),
       ('Display Interface Transceivers', 7),
       ('Distance Sensors', 7),
       ('Electric Solenoids', 7),
       ('Electrolytic Capacitors', 7),
       ('Encoder Sensors', 7),
       ('Ethernet Controllers', 7),
       ('Ethernet Modules', 7),
       ('Ethernet Switches', 7),
       ('Ethernet Transceivers', 7),
       ('Ferrite Beads', 7),
       ('Film Capacitors', 7),
       ('Flex Sensors', 7),
       ('Flexible Printed Circuits', 7),
       ('Flow Sensors', 7),
       ('Force Sensors', 7),
       ('Frequency Synthesizer ICs', 7),
       ('Frequency Synthesizers', 7),
       ('Fuses', 7),
       ('Gas Detectors', 7),
       ('Gas Sensors', 7),
       ('GPS Modules', 7),
       ('GPS Receivers', 7),
       ('Graphic LCD Modules', 7),
       ('Gyroscopes', 7),
       ('Hall Effect Proximity Sensors', 7),
       ('Hall Effect Sensors', 7),
       ('Hall Effect Switches', 7),
       ('Heat Sinks', 7),
       ('High-Power LEDs', 7),
       ('Humidity Sensors', 7),
       ('I2C Transceivers', 7),
       ('Inclinometers', 7),
       ('Inductors', 7),
       ('Integrated Circuit Sockets', 7),
       ('Integrated Circuits (ICs)', 7),
       ('IR Emitters', 7),
       ('IR LEDs', 7),
       ('IR Receivers', 7),
       ('IR Sensors', 7),
       ('LAN Transformers', 7),
       ('Laser Alignment Modules', 7),
       ('Laser Diode Modules', 7),
       ('Laser Diodes', 7),
       ('Laser Distance Sensors', 7),
       ('Laser Drivers', 7),
       ('Laser Modules', 7),
       ('Laser Rangefinders', 7),
       ('Laser Sensors', 7),
       ('LCDs (Liquid Crystal Displays)', 7),
       ('LED Arrays', 7),
       ('LED Displays', 7),
       ('LED Drivers', 7),
       ('LED Strips', 7),
       ('LEDs (Light Emitting Diodes)', 7),
       ('Light Sensors', 7),
       ('Linear Encoders', 7),
       ('Linear Motors', 7),
       ('Load Cells', 7),
       ('LoRa Adapters', 7),
       ('LoRa Controllers', 7),
       ('LoRa Modules', 7),
       ('LoRa Transceivers', 7),
       ('Magnetic Sensors', 7),
       ('Magnetometers', 7),
       ('MEMS Oscillators', 7),
       ('Microcontrollers', 7),
       ('MOSFETs (Metal-Oxide-Semiconductor Field-Effect Transistors)', 7),
       ('Motion Sensors', 7),
       ('Motor Controllers', 7),
       ('Motor Drivers', 7),
       ('Multilayer Ceramic Capacitors', 7),
       ('NFC Modules', 7),
       ('OLED Displays', 7),
       ('Op-amps (Operational Amplifiers)', 7),
       ('Optical Sensors', 7),
       ('Optocouplers', 7),
       ('Optoisolators', 7),
       ('Oscillator ICs', 7),
       ('Parallel Interface Transceivers', 7),
       ('Phase-Locked Loop (PLL) ICs', 7),
       ('Photo Detectors', 7),
       ('Photodiodes', 7),
       ('Photoelectric Sensors', 7),
       ('Photoresistors', 7),
       ('Phototransistors', 7),
       ('Piezoelectric Transducers', 7),
       ('Position Sensors', 7),
       ('Potentiometers', 7),
       ('Power Amplifiers', 7),
       ('Pressure Sensors', 7),
       ('Pressure Transducers', 7),
       ('Proximity Sensors', 7),
       ('Quartz Oscillators', 7),
       ('Relays', 7),
       ('Resistor Networks', 7),
       ('Resistors', 7),
       ('RF Adapter ICs', 7),
       ('RF Adapters', 7),
       ('RF Amplifier ICs', 7),
       ('RF Antenna ICs', 7),
       ('RF Antennas', 7),
       ('RF Attenuator ICs', 7),
       ('RF Attenuators', 7),
       ('RF Balun ICs', 7),
       ('RF Baluns', 7),
       ('RF Cable Assemblies', 7),
       ('RF Cable Assembly ICs', 7),
       ('RF Circulator ICs', 7),
       ('RF Circulators', 7),
       ('RF Combiner ICs', 7),
       ('RF Combiners', 7),
       ('RF Connector ICs', 7),
       ('RF Connectors', 7),
       ('RF Coupler ICs', 7),
       ('RF Couplers', 7),
       ('RF Demodulator ICs', 7),
       ('RF Demodulators', 7),
       ('RF Diode Detectors', 7),
       ('RF Duplexer ICs', 7),
       ('RF Duplexers', 7),
       ('RF Equalizer ICs', 7),
       ('RF Equalizers', 7),
       ('RF Filter ICs', 7),
       ('RF Filters', 7),
       ('RF Frequency Counters', 7),
       ('RF Frequency Synthesizer ICs', 7),
       ('RF Isolator ICs', 7),
       ('RF Isolators', 7),
       ('RF Limiter ICs', 7),
       ('RF Limiters', 7),
       ('RF Limiting Amplifier ICs', 7),
       ('RF Low-Noise Amplifier (LNA) ICs', 7),
       ('RF Mixer ICs', 7),
       ('RF Mixers', 7),
       ('RF Modulator ICs', 7),
       ('RF Modulators', 7),
       ('RF Noise Generator ICs', 7),
       ('RF Noise Generators', 7),
       ('RF Oscilloscopes', 7),
       ('RF Phase Shifter ICs', 7),
       ('RF Phase Shifters', 7),
       ('RF Phase-Locked Loop (PLL) ICs', 7),
       ('RF Power Amplifier ICs', 7),
       ('RF Power Amplifiers', 7),
       ('RF Power Divider ICs', 7),
       ('RF Power Dividers', 7),
       ('RF Power Meters', 7),
       ('RF Signal Amplifier ICs', 7),
       ('RF Signal Amplifiers', 7),
       ('RF Signal Attenuator ICs', 7),
       ('RF Signal Attenuators', 7),
       ('RF Signal Balun ICs', 7),
       ('RF Signal Baluns', 7),
       ('RF Signal Conditioners', 7),
       ('RF Signal Converters', 7),
       ('RF Signal Demodulator ICs', 7),
       ('RF Signal Demodulators', 7),
       ('RF Signal Detector ICs', 7),
       ('RF Signal Detectors', 7),
       ('RF Signal Filter ICs', 7),
       ('RF Signal Filters', 7),
       ('RF Signal Generators', 7),
       ('RF Signal Mixer ICs', 7),
       ('RF Signal Modulator ICs', 7),
       ('RF Signal Modulators', 7),
       ('RF Signal Switch ICs', 7),
       ('RF Signal Switches', 7),
       ('RF Spectrum Analyzers', 7),
       ('RF Splitter ICs', 7),
       ('RF Splitters', 7),
       ('RF Switch ICs', 7),
       ('RF Switches', 7),
       ('RF Terminator ICs', 7),
       ('RF Terminators', 7),
       ('RF Transceivers', 7),
       ('RF Transistor Amplifiers', 7),
       ('RF Triplexer ICs', 7),
       ('RF Triplexers', 7),
       ('RF Vector Network Analyzers', 7),
       ('RF Voltage-Controlled Amplifier (VCA) ICs', 7),
       ('RF Voltage-Controlled Filter (VCF) ICs', 7),
       ('RF Voltage-Controlled Oscillator (VCO) ICs', 7),
       ('RFID Modules', 7),
       ('RFID Readers', 7),
       ('RFID Tags', 7),
       ('RGB LEDs', 7),
       ('Rotary Encoders', 7),
       ('RS-232 Transceivers', 7),
       ('RS-422 Transceivers', 7),
       ('RS-485 Transceivers', 7),
       ('Semiconductor Testers', 7),
       ('Sensors', 7),
       ('Servo Motors', 7),
       ('Signal Amplifiers', 7),
       ('Signal Filters', 7),
       ('Smoke Detectors', 7),
       ('Soldering Irons', 7),
       ('Soldering Stations', 7),
       ('Sound Sensors', 7),
       ('SPI Transceivers', 7),
       ('Stepper Motors', 7),
       ('Switches', 7),
       ('Tantalum Capacitors', 7),
       ('Temperature Sensors', 7),
       ('TFT LCD Displays', 7),
       ('Thermal Compounds', 7),
       ('Thermal Sensors', 7),
       ('Thermistors', 7),
       ('Thyristors', 7),
       ('Timing Crystals', 7),
       ('Transformers', 7),
       ('Transistors', 7),
       ('UART Transceivers', 7),
       ('Ultrasonic Distance Sensors', 7),
       ('Ultrasonic Sensors', 7),
       ('Ultraviolet (UV) Sensors', 7),
       ('USB Bridges', 7),
       ('USB Host Controllers', 7),
       ('USB Hubs', 7),
       ('USB Interfaces', 7),
       ('UV LEDs', 7),
       ('Varistors', 7),
       ('Vibration Sensors', 7),
       ('Voltage Detectors', 7),
       ('Voltage Dividers', 7),
       ('Voltage References', 7),
       ('Voltage Regulators', 7),
       ('Voltage Supervisors', 7),
       ('Voltage Translators', 7),
       ('Voltage-Controlled Oscillators (VCOs)', 7),
       ('Voltage-Controlled Oscillators', 7),
       ('WiFi Controllers', 7),
       ('WiFi Modules', 7),
       ('WiFi Transceivers', 7),
       ('WLAN Adapters', 7),
       ('WLAN Controllers', 7),
       ('WLAN Modules', 7),
       ('WLAN Transceivers', 7),
       ('Zener Diodes', 7),
       ('Zigbee Adapters', 7),
       ('Zigbee Controllers', 7),
       ('Zigbee Modules', 7),
       ('Zigbee Transceivers', 7) ON CONFLICT
    DO NOTHING;
