-- Electronics
INSERT INTO component_type (name, hardware_category_id)
VALUES ('Ammeter', 8),
       ('Anemometer (Wind Speed Meter)', 8),
       ('Barometer', 8),
       ('Blood Pressure Monitor', 8),
       ('Capacitance Meter', 8),
       ('Digital Analyzer', 8),
       ('Distortion Analyzer', 8),
       ('ECG Machine (Electrocardiogram)', 8),
       ('EEG Machine (Electroencephalogram)', 8),
       ('EMI/EMC Test Equipment', 8),
       ('ESD Test Equipment', 8),
       ('Frequency Counter', 8),
       ('Function Generator', 8),
       ('Gas Detector', 8),
       ('Gauss Meter', 8),
       ('Geiger Counter', 8),
       ('Harmonic Analyzer', 8),
       ('Hygrometer', 8),
       ('Impedance Analyzer', 8),
       ('Inductance Meter', 8),
       ('Infrared Thermometer', 8),
       ('LCR Meter (Inductance, Capacitance, Resistance)', 8),
       ('Logic Analyzer', 8),
       ('Luxmeter (Light Meter)', 8),
       ('Magnetic Field Meter', 8),
       ('Multimeter', 8),
       ('Network Analyzer', 8),
       ('Oscilloscope', 8),
       ('pH Meter', 8),
       ('Power Analyzer', 8),
       ('Power Supply', 8),
       ('Pulse Oximeter', 8),
       ('Radiation Detector', 8),
       ('RF Antenna Analyzer', 8),
       ('RF Field Strength Meter', 8),
       ('RF Modulation Analyzer', 8),
       ('RF Network Analyzer', 8),
       ('RF Noise Figure Meter', 8),
       ('RF Oscilloscope', 8),
       ('RF Power Meter', 8),
       ('RF Signal Generator', 8),
       ('RF Spectrum Analyzer', 8),
       ('RF Vector Network Analyzer', 8),
       ('RF Vector Signal Analyzer', 8),
       ('Signal Analyzer', 8),
       ('Signal Generator', 8),
       ('Sound Level Meter', 8),
       ('Spectrum Analyzer', 8),
       ('Thermal Imaging Camera', 8),
       ('Thermometer', 8),
       ('UV Meter (Ultraviolet Light Meter)', 8),
       ('Vector Network Analyzer (VNA)', 8),
       ('Vector Signal Generator', 8),
       ('Vibration Meter', 8),
       ('Voltmeter', 8)
ON CONFLICT
    DO NOTHING;
