INSERT INTO software_publisher (name)
VALUES ('2K Games'),
       ('Acclaim Entertainment'),
       ('Activision Blizzard'),
       ('Atari'),
       ('Bandai Namco Entertainment'),
       ('Bethesda Softworks'),
       ('BioWare'),
       ('Blizzard Entertainment'),
       ('Bullfrog Productions'),
       ('Capcom'),
       ('CD Projekt'),
       ('Codemasters'),
       ('Eidos Interactive'),
       ('Electronic Arts'),
       ('Enix'),
       ('Epic Games'),
       ('id Software'),
       ('Infogrames'),
       ('Konami'),
       ('LucasArts'),
       ('Maxis'),
       ('Microsoft Game Studios'),
       ('Midway Games'),
       ('Namco'),
       ('Nintendo'),
       ('Origin Systems'),
       ('Psygnosis'),
       ('Rockstar Games'),
       ('Sega'),
       ('Sierra Entertainment'),
       ('Sony Interactive Entertainment'),
       ('Square Enix'),
       ('Take-Two Interactive'),
       ('THQ'),
       ('Ubisoft'),
       ('Valve Corporation'),
       ('Vivendi Games'),
       ('Westwood Studios') ON CONFLICT
    DO NOTHING;
