INSERT INTO software_developer (name)
VALUES ('Accolade'),
       ('Acquire'),
       ('AlphaDream'),
       ('Ambrella'),
       ('Ankama Games'),
       ('Annapurna Interactive'),
       ('Arc System Works'),
       ('ArenaNet'),
       ('Arika'),
       ('Artdink'),
       ('ArtePiazza'),
       ('Artificial Mind and Movement (A2M)'),
       ('Ascaron'),
       ('Asobo Studio'),
       ('Aspyr'),
       ('Atari'),
       ('Atlus'),
       ('Avalanche Studios'),
       ('Behaviour Interactive'),
       ('Bethesda Game Studios'),
       ('Big Huge Games'),
       ('BioWare'),
       ('Black Isle Studios'),
       ('Blizzard Entertainment'),
       ('Blue Byte'),
       ('Bungie'),
       ('Capcom'),
       ('CD Projekt Red'),
       ('Chucklefish'),
       ('Cing'),
       ('Clap Hanz'),
       ('Clover Studio'),
       ('Codemasters'),
       ('Coktel Vision'),
       ('Colossal Order'),
       ('Compile Heart'),
       ('Core Design'),
       ('Crafts & Meister'),
       ('Creative Assembly'),
       ('Croteam'),
       ('Cryo Interactive'),
       ('Crystal Dynamics'),
       ('Cyan Worlds'),
       ('CyberConnect2'),
       ('D3 Publisher'),
       ('Daedalic Entertainment'),
       ('Deck13'),
       ('Deep Silver'),
       ('Delphine Software International'),
       ('Digital Extremes'),
       ('Digital Illusions CE (DICE)'),
       ('Dimps'),
       ('Dontnod Entertainment'),
       ('Double Fine Productions'),
       ('Dovetail Games'),
       ('Eidos Montreal'),
       ('Electronic Arts'),
       ('Ensemble Studios'),
       ('Epic Games'),
       ('Falcom'),
       ('Feral Interactive'),
       ('Firaxis Games'),
       ('Flying Wild Hog'),
       ('FromSoftware'),
       ('Frontier Developments'),
       ('Frostbite Labs'),
       ('Game Freak'),
       ('Gearbox Software'),
       ('Genius Sonority'),
       ('Ghost Games'),
       ('Giant Sparrow'),
       ('Good-Feel'),
       ('Gorilla Systems'),
       ('Grasshopper Manufacture'),
       ('Griptonite Games'),
       ('GSC Game World'),
       ('Guerrilla Games'),
       ('Gungho Online Entertainment'),
       ('Gust Co. Ltd.'),
       ('HAL Laboratory'),
       ('Harebrained Schemes'),
       ('Harmonix'),
       ('Headstrong Games'),
       ('Heart Machine'),
       ('Hello Games'),
       ('High Voltage Software'),
       ('Housemarque'),
       ('Hudson Soft'),
       ('Human Entertainment'),
       ('id Software'),
       ('Idea Factory'),
       ('Imageepoch'),
       ('Infinity Ward'),
       ('inXile Entertainment'),
       ('IO Interactive'),
       ('Ion Storm'),
       ('Irem'),
       ('Irrational Games'),
       ('Ivory Tower'),
       ('Jagex'),
       ('Jaleco'),
       ('Jupiter Corporation'),
       ('Kadokawa Games'),
       ('Kalypso Media'),
       ('Keen Games'),
       ('Kemco'),
       ('KID'),
       ('Klei Entertainment'),
       ('Koei Tecmo'),
       ('Konami'),
       ('Krome Studios'),
       ('Kunos Simulazioni'),
       ('Level-5'),
       ('Lionhead Studios'),
       ('LucasArts'),
       ('M2'),
       ('MachineGames'),
       ('Marvellous'),
       ('Masaya Games'),
       ('Massive Entertainment'),
       ('Maxis'),
       ('Media Molecule'),
       ('Media.Vision'),
       ('MercurySteam'),
       ('MicroProse'),
       ('Midway Games'),
       ('Milestone S.r.l.'),
       ('Mistwalker'),
       ('Mitchell Corporation'),
       ('Monolith Productions'),
       ('Monolith Soft'),
       ('Motion Twin'),
       ('MTO Co., Ltd.'),
       ('Naughty Dog'),
       ('NCsoft'),
       ('NetherRealm Studios'),
       ('Nexon'),
       ('Next Level Games'),
       ('Nihon Falcom'),
       ('Nintendo'),
       ('Nippon Ichi Software'),
       ('Nitroplus'),
       ('Nival'),
       ('No More Robots'),
       ('Nordic Games'),
       ('NovaLogic'),
       ('Obsidian Entertainment'),
       ('Oddworld Inhabitants'),
       ('Omega Force'),
       ('Origin Systems'),
       ('Other Ocean Interactive'),
       ('Outfit7'),
       ('Overkill Software'),
       ('Pandemic Studios'),
       ('Paradox Interactive'),
       ('Pendulo Studios'),
       ('People Can Fly'),
       ('Piranha Bytes'),
       ('Pixelopus'),
       ('Playdead'),
       ('PlatinumGames'),
       ('Polyphony Digital'),
       ('PopCap Games'),
       ('Psyonix'),
       ('Quantic Dream'),
       ('Rare'),
       ('Raven Software'),
       ('Ready at Dawn'),
       ('Rebellion Developments'),
       ('Red Barrels'),
       ('RedLynx'),
       ('Remedy Entertainment'),
       ('Respawn Entertainment'),
       ('Retro Studios'),
       ('Rockstar Games'),
       ('Rocksteady Studios'),
       ('Rovio Entertainment'),
       ('Ryu Ga Gotoku Studio'),
       ('Saber Interactive'),
       ('SCE Japan Studio'),
       ('SCE Santa Monica Studio'),
       ('Schell Games'),
       ('Sega'),
       ('SIE Bend Studio'),
       ('SIE Japan Studio'),
       ('SIE London Studio'),
       ('SIE San Diego Studio'),
       ('Sierra Entertainment'),
       ('Silicon Knights'),
       ('Silicon Studio'),
       ('Sledgehammer Games'),
       ('Slightly Mad Studios'),
       ('SNK'),
       ('Sony Interactive Entertainment'),
       ('Sora Ltd.'),
       ('Spike Chunsoft'),
       ('Square Enix'),
       ('Stainless Games'),
       ('Starbreeze Studios'),
       ('Sting Entertainment'),
       ('Stormfront Studios'),
       ('Studio MDHR'),
       ('Subset Games'),
       ('Sucker Punch Productions'),
       ('Sumo Digital'),
       ('Sunsoft'),
       ('Supermassive Games'),
       ('SystemSoft Alpha'),
       ('Taito Corporation'),
       ('TaleWorlds Entertainment'),
       ('Tango Gameworks'),
       ('Team17'),
       ('Tecmo'),
       ('Telltale Games'),
       ('THQ'),
       ('THQ Nordic'),
       ('Three Rings Design'),
       ('Toby Fox'),
       ('Tokyo RPG Factory'),
       ('Toys for Bob'),
       ('Travellers Tales'),
       ('Treasure'),
       ('Tri-Ace'),
       ('Tribute Games'),
       ('Tripwire Interactive'),
       ('Troika Games'),
       ('Turn 10 Studios'),
       ('Ubisoft'),
       ('Ubisoft Annecy'),
       ('Ubisoft Montpellier'),
       ('Ubisoft Montreal'),
       ('Ubisoft Reflections'),
       ('Ubisoft San Francisco'),
       ('Ubisoft Toronto'),
       ('Ultimate Play The Game'),
       ('United Front Games'),
       ('Valve Corporation'),
       ('Vanillaware'),
       ('Vicarious Visions'),
       ('Vigil Games'),
       ('Visceral Games'),
       ('Visual Concepts'),
       ('Volition'),
       ('Warner Bros. Interactive Entertainment'),
       ('WayForward Technologies'),
       ('Westwood Studios'),
       ('White Owls Inc.'),
       ('Yacht Club Games'),
       ('Yager Development'),
       ('Yukes'),
       ('Zen Studios'),
       ('ZeniMax Online Studios'),
       ('Zipper Interactive')
ON CONFLICT
    DO NOTHING;
