INSERT INTO software_platform (name)
VALUES ('3DO'),
       ('Amiga'),
       ('Android'),
       ('Apple II'),
       ('Arcade'),
       ('Atari 2600'),
       ('Atari 5200'),
       ('Atari 7800'),
       ('Atari Jaguar'),
       ('Atari Lynx'),
       ('BlackBerry OS'),
       ('ColecoVision'),
       ('Commodore 64'),
       ('DOS'),
       ('Dreamcast'),
       ('Game Boy'),
       ('Game Boy Advance'),
       ('Game Boy Color'),
       ('GameCube'),
       ('Genesis'),
       ('iOS'),
       ('Linux'),
       ('Mac'),
       ('Master System'),
       ('Neo Geo'),
       ('Neo Geo Pocket Color'),
       ('NES (Nintendo Entertainment System)'),
       ('Nintendo 3DS'),
       ('Nintendo 64'),
       ('Nintendo DS'),
       ('Nintendo Switch'),
       ('PC'),
       ('PlayStation'),
       ('PlayStation 2'),
       ('PlayStation 3'),
       ('PlayStation 4'),
       ('PlayStation 5'),
       ('PlayStation Portable (PSP)'),
       ('PlayStation Vita'),
       ('Sega CD'),
       ('Sega Game Gear'),
       ('Sega Saturn'),
       ('SNES (Super Nintendo)'),
       ('TurboGrafx-16'),
       ('Virtual Boy'),
       ('Wii'),
       ('Wii U'),
       ('Windows'),
       ('Xbox'),
       ('Xbox 360'),
       ('Xbox One'),
       ('Xbox Series X/S'),
       ('ZX Spectrum')
ON CONFLICT
    DO NOTHING;
