INSERT INTO hardware_category (name)
VALUES ('Computer Hardware')

ON CONFLICT
    DO NOTHING;
-- Computer Hardware
INSERT INTO component_type (name, hardware_category_id)
VALUES ('80 PLUS Bronze PSUs', 6),
       ('80 PLUS Certified PSUs', 6),
       ('80 PLUS Gold PSUs', 6),
       ('80 PLUS Platinum PSUs', 6),
       ('80 PLUS Silver PSUs', 6),
       ('80 PLUS Titanium PSUs', 6),
       ('AIO Liquid Coolers', 6),
       ('Anti-Static Wrist Strap', 6),
       ('ATX Cases', 6),
       ('ATX Power Supplies', 6),
       ('Audio Port', 6),
       ('Bluetooth Adapter', 6),
       ('Bluetooth Speaker', 6),
       ('Cable Accessories', 6),
       ('Cable Adapters', 6),
       ('Cable Clips', 6),
       ('Cable Combs', 6),
       ('Cable Connectors', 6),
       ('Cable Converters', 6),
       ('Cable Cover', 6),
       ('Cable Extensions', 6),
       ('Cable Grommet', 6),
       ('Cable Holders', 6),
       ('Cable Labels', 6),
       ('Cable Management Accessories', 6),
       ('Cable Management Box', 6),
       ('Cable Management Channel', 6),
       ('Cable Management Kit', 6),
       ('Cable Management Panel', 6),
       ('Cable Management Sleeve', 6),
       ('Cable Management', 6),
       ('Cable Organizer Box', 6),
       ('Cable Organizer', 6),
       ('Cable Organizers', 6),
       ('Cable Pass Through', 6),
       ('Cable Raceway', 6),
       ('Cable Sleeves', 6),
       ('Cable Splitters', 6),
       ('Cable Ties', 6),
       ('Cable Tray', 6),
       ('Cable Wall Plate', 6),
       ('Case Accessories', 6),
       ('Case Bottom Panels', 6),
       ('Case Cooling Fans', 6),
       ('Case Cooling', 6),
       ('Case Fan', 6),
       ('Case Fans', 6),
       ('Case Filters', 6),
       ('Case Front Panels', 6),
       ('Case Handles', 6),
       ('Case Latches', 6),
       ('Case Lighting', 6),
       ('Case Locks', 6),
       ('Case Mods', 6),
       ('Case Rear Panels', 6),
       ('Case Side Panels', 6),
       ('Case Top Panels', 6),
       ('Case Wheels', 6),
       ('CPU (Central Processing Unit)', 6),
       ('Chair', 6),
       ('Computer Case Panels', 6),
       ('Computer Case Screws', 6),
       ('Computer Case', 6),
       ('Computer Cases', 6),
       ('Computer Power Supplies', 6),
       ('Computer Vacuum', 6),
       ('Cooling Accessories', 6),
       ('Cooling Fan', 6),
       ('CPU Cooler', 6),
       ('CPU Coolers', 6),
       ('CPU Cooling Fans', 6),
       ('CPU Fans', 6),
       ('CPU Heatsinks', 6),
       ('CPU Thermal Paste', 6),
       ('Custom Loop Water Cooling', 6),
       ('Desk Accessories', 6),
       ('Desk Cable Management', 6),
       ('Desk', 6),
       ('Display Cable', 6),
       ('Docking Station', 6),
       ('Driver Disc', 6),
       ('Dust Filter', 6),
       ('E-ATX Cases', 6),
       ('Ergonomic Mouse Pad', 6),
       ('Ethernet Port', 6),
       ('External Blu-ray Drive', 6),
       ('External Graphics Card Enclosure', 6),
       ('External Hard Drive', 6),
       ('External Microphone', 6),
       ('External Optical Drive', 6),
       ('External Sound Card', 6),
       ('External SSD', 6),
       ('External Webcam', 6),
       ('Fan Controllers', 6),
       ('Fan Filters', 6),
       ('Full-Tower Cases', 6),
       ('Fully Modular Power Supplies', 6),
       ('Gaming Chair', 6),
       ('Gaming Controller', 6),
       ('Gaming Desk Accessories', 6),
       ('Gaming Desk', 6),
       ('Gaming Headset', 6),
       ('Gaming Keyboard', 6),
       ('Gaming Mouse Pad', 6),
       ('Gaming Mouse', 6),
       ('GPU Coolers', 6),
       ('GPU Cooling Fans', 6),
       ('GPU Fans', 6),
       ('GPU Water Blocks', 6),
       ('Graphics Card Cooler', 6),
       ('GPU (Graphics Processing Unit)', 6),
       ('Hard Disk Drive (HDD)', 6),
       ('Headset', 6),
       ('Heatsink Compounds', 6),
       ('HTPC Cases', 6),
       ('Internal Cables', 6),
       ('Internal Connectors', 6),
       ('Keyboard', 6),
       ('KVM Switch', 6),
       ('M.2 Heatsinks', 6),
       ('Mechanical Keyboard', 6),
       ('Micro ATX Cases', 6),
       ('Micro ATX Power Supplies', 6),
       ('Microfiber Cloth', 6),
       ('Microphone', 6),
       ('Mid-Tower Cases', 6),
       ('Mini ITX Cases', 6),
       ('Modular Power Supplies', 6),
       ('Monitor Arm Mount', 6),
       ('Monitor Cleaning Kit', 6),
       ('Monitor Desk Mount', 6),
       ('Monitor Privacy Screen', 6),
       ('Monitor Stand', 6),
       ('Monitor Wall Mount', 6),
       ('Monitor', 6),
       ('Motherboard Chipset Fans', 6),
       ('Motherboard', 6),
       ('Mounting Bracket', 6),
       ('Mouse Pad', 6),
       ('Mouse', 6),
       ('Network Interface Card (NIC)', 6),
       ('Northbridge Heatsinks', 6),
       ('Optical Drive', 6),
       ('PC Case Feet', 6),
       ('PC Cleaning Kit', 6),
       ('PC Cooling Fans', 6),
       ('PC Cooling Solutions', 6),
       ('PC Repair Software', 6),
       ('PC Stand', 6),
       ('PC Tool Kit', 6),
       ('PCIe Slot', 6),
       ('Power Cable', 6),
       ('Power Cables', 6),
       ('Power Cord Extensions', 6),
       ('Power Supply Accessories', 6),
       ('Power Supply Unit (PSU)', 6),
       ('Power Supply Units', 6),
       ('RAM Heatsinks', 6),
       ('RAM Slot', 6),
       ('RAM (Random Access Memory)', 6),
       ('RGB Cases', 6),
       ('RGB Fans', 6),
       ('RGB Lighting Kit', 6),
       ('RGB Mouse Pad', 6),
       ('SATA Cable', 6),
       ('SATA Port', 6),
       ('Semi-Modular Power Supplies', 6),
       ('SFX Power Supplies', 6),
       ('SSD (Solid State Drive)', 6),
       ('Sound Card', 6),
       ('Southbridge Heatsinks', 6),
       ('Speakers', 6),
       ('Storage Drive Bay', 6),
       ('Thermal Adhesive', 6),
       ('Thermal Compound', 6),
       ('Thermal Conductive Pad', 6),
       ('Thermal Grease', 6),
       ('Thermal Insulators', 6),
       ('Thermal Interface Material', 6),
       ('Thermal Management', 6),
       ('Thermal Pads', 6),
       ('Thermal Paste', 6),
       ('Thermal Tape', 6),
       ('UPS (Uninterruptible Power Supply)', 6),
       ('USB Cable', 6),
       ('USB Hub', 6),
       ('USB Port', 6),
       ('User Manual', 6),
       ('VRM Cooling Fans', 6),
       ('VRM Heatsinks', 6),
       ('Webcam', 6),
       ('Wi-Fi Card', 6),
       ('Wireless Antenna', 6),
       ('Wireless Charging Accessories', 6),
       ('Wireless Charging Dock', 6),
       ('Wireless Charging Mat', 6),
       ('Wireless Charging Pad', 6),
       ('Wireless Charging Stand', 6),
       ('Wireless Keyboard and Mouse Combo', 6),
       ('Wireless Keyboard', 6),
       ('Wireless Mouse', 6)
ON CONFLICT
    DO NOTHING;