INSERT INTO hardware_brand (name)
VALUES ('Atari Games'),
       ('Bally Technologies'),
       ('Capcom Arcade'),
       ('Data East Classics'),
       ('Eldorado Arcade Co.'),
       ('FunSpot Arcades'),
       ('GameWorks Manufacturing'),
       ('House of Arcades'),
       ('Incredible Technologies'),
       ('Jubilee Arcade Makers'),
       ('Konami Amusement'),
       ('Legacy Arcade Crafters'),
       ('Midway Classics'),
       ('Namco Entertainment'),
       ('Ocean Star Arcades'),
       ('Playtime Arcade Builders'),
       ('Quantum Arcades'),
       ('RetroArcade Crafters'),
       ('Sega Amusements'),
       ('Taito Corporation'),
       ('Ultimate Arcades'),
       ('Vanguard Arcade Systems'),
       ('Williams Electronics'),
       ('Xtreme Arcade Makers'),
       ('YellowSubmarine Arcades'),
       ('ZapCon Arcade Manufacturing')
ON CONFLICT
    DO NOTHING;
