INSERT INTO hardware_brand (name)
VALUES ('Adidas'),
       ('Asics'),
       ('Babolat'),
       ('Burton Snowboards'),
       ('Callaway'),
       ('Columbia Sportswear'),
       ('Easton'),
       ('Garmin'),
       ('Life Fitness'),
       ('Merrell'),
       ('Mizuno'),
       ('New Balance'),
       ('Nike'),
       ('Patagonia'),
       ('Ping'),
       ('Puma'),
       ('Rawlings'),
       ('Reebok'),
       ('Salomon'),
       ('Schwinn'),
       ('Speedo'),
       ('Spalding'),
       ('Specialized'),
       ('Suunto'),
       ('The North Face'),
       ('Titleist'),
       ('Trek'),
       ('Under Armour'),
       ('Wilson'),
       ('Yonex')
ON CONFLICT
    DO NOTHING;
