#!/bin/bash

cd "$(dirname "$0")"
# shellcheck disable=SC2103
cd ..

echo "Starting Docker environment cleanup..."

echo "Stopping containers and removing containers, networks..."
docker compose down

echo "Removing all images and volumes..."
docker compose down --rmi all --volumes

echo "Volume prune"
docker volume prune --force

echo "System-wide prune"
docker system prune --all --force

echo "Docker environment cleanup completed successfully."
