INSERT INTO hardware_brand (name)
VALUES ('3Com'),
       ('3dfx'),
       ('ADATA'),
       ('AMD'),
       ('AOC'),
       ('APC'),
       ('ASRock'),
       ('AST Research'),
       ('ASUS'),
       ('Abit'),
       ('Acer'),
       ('Acorn Computers'),
       ('Adaptec'),
       ('Adata'),
       ('Allied Telesis'),
       ('Altec Lansing'),
       ('Amiga'),
       ('Amstrad'),
       ('Antec'),
       ('Apple Inc.'),
       ('Apricot Computers'),
       ('Arctic'),
       ('Asus'),
       ('Atari'),
       ('BFG Technologies'),
       ('Belinea'),
       ('BenQ'),
       ('Biostar'),
       ('Brother'),
       ('Brother Industries'),
       ('Canon'),
       ('Casio'),
       ('Cherry'),
       ('Cisco Systems'),
       ('Commodore International'),
       ('Compaq'),
       ('Cooler Master'),
       ('Corsair'),
       ('Creative'),
       ('Creative Technology'),
       ('Crucial'),
       ('Cyrix'),
       ('DELL'),
       ('Deepcool'),
       ('Dell'),
       ('Diamond Multimedia'),
       ('Digital Equipment Corporation'),
       ('Dynatron'),
       ('EVGA'),
       ('Ensoniq'),
       ('Epson'),
       ('FIC (First International Computer)'),
       ('FSP Group'),
       ('Fractal Design'),
       ('Freecom'),
       ('Fujitsu'),
       ('G.Skill'),
       ('Gateway, Inc.'),
       ('Gericom'),
       ('Gigabyte'),
       ('Gigabyte Technology'),
       ('Glorious PC Gaming Race'),
       ('HGST'),
       ('HP'),
       ('Hercules'),
       ('Hewlett-Packard (HP)'),
       ('Hitachi'),
       ('HyperX'),
       ('IBM'),
       ('IBM (PC division)'),
       ('InWin'),
       ('Inno3D'),
       ('InnoDisk'),
       ('Intel'),
       ('Iomega'),
       ('JVC'),
       ('Jonsbo'),
       ('KFA2'),
       ('Kaspersky'),
       ('Kingston'),
       ('Kingston Technology'),
       ('Kyocera'),
       ('LG'),
       ('LG Electronics'),
       ('Leadtek'),
       ('Lenovo'),
       ('Lite-On'),
       ('Logitech'),
       ('MSI'),
       ('Magitronic'),
       ('Matrox'),
       ('Maxtor'),
       ('Micron Electronics'),
       ('Microsoft'),
       ('Mushkin'),
       ('NEC'),
       ('NVIDIA'),
       ('NZXT'),
       ('Nec'),
       ('Netgear'),
       ('OCZ'),
       ('Olivetti'),
       ('Orchid Technology'),
       ('PNY'),
       ('Packard Bell'),
       ('Panasonic'),
       ('Patriot'),
       ('Phanteks'),
       ('Philips'),
       ('Pioneer'),
       ('PioneerPlantronics'),
       ('Plantronics'),
       ('PowerColor'),
       ('Qnap'),
       ('Quantum'),
       ('Quantum3D'),
       ('Razer Inc.'),
       ('Ricoh'),
       ('Roccat'),
       ('S3 Graphics'),
       ('SIS (Silicon Integrated Systems)'),
       ('STB Systems'),
       ('STMicroelectronics'),
       ('Samsung'),
       ('Samsung Electronics'),
       ('SanDisk'),
       ('Sapphire'),
       ('Seagate'),
       ('Seagate Technology'),
       ('Sennheiser'),
       ('Sharp Corporation'),
       ('Shuttle'),
       ('SilverStone'),
       ('Sonnet Technologies'),
       ('Sony'),
       ('SteelSeries'),
       ('Sun Microsystems'),
       ('Tandy Corporation'),
       ('Tenda'),
       ('Tesoro'),
       ('Texas Instruments'),
       ('Thermaltake'),
       ('Toshiba'),
       ('Transcend'),
       ('Trident Microsystems'),
       ('Turtle Beach'),
       ('Tyan'),
       ('Unisys'),
       ('VIA'),
       ('VIA Technologies'),
       ('ViewSonic'),
       ('VoodooPC'),
       ('Western Digital'),
       ('XFX'),
       ('Xerox'),
       ('Xiaomi'),
       ('Zalman'),
       ('Zenith Data Systems'),
       ('Zotac') ON CONFLICT
    DO NOTHING;